name: hw1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  cached_network_image: ^3.3.1
  webview_flutter: ^4.5.0
  webview_flutter_web: ^0.2.2+4
  url_launcher: ^6.2.4
  flutter_lints: ^3.0.1
  provider: ^6.1.2
  flutter_bloc: ^8.1.4
  flutter_riverpod: ^2.4.10
  freezed_annotation: ^2.4.1
  freezed: ^2.4.7
  build_runner: ^2.4.6
  rxdart: ^0.27.7

  cupertino_icons: ^1.0.2

dev_dependencies:
  test: ^1.24.9
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true